# Generated by Django 4.2.27 on 2026-02-13 05:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('candidates', '0001_initial'), ('candidates', '0002_candidateeducation_candidateemployment_and_more'), ('candidates', '0003_candidateprofile_availability_to_join_and_more'), ('candidates', '0004_candidateeducation_course_type_and_marks'), ('candidates', '0005_candidateproject_status_and_dates'), ('candidates', '0005_alter_candidateeducation_course_type_and_more'), ('candidates', '0006_merge_20260211_1122'), ('candidates', '0007_alter_candidateeducation_course_type_and_more'), ('candidates', '0006_candidateprofile_personal_details'), ('candidates', '0008_merge_20260212_1052'), ('candidates', '0007_candidateprofile_salary_currency'), ('candidates', '0009_merge_20260212_1133')]

    dependencies = [
        ('accounts', '0002_update_roles_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('notice_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('total_experience_months', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('total_experience_years', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_to_join', models.CharField(blank=True, max_length=30)),
                ('location_country', models.CharField(default='India', max_length=60)),
                ('photo_file', models.FileField(blank=True, null=True, upload_to='profile-photos/')),
                ('work_status', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('current_city', models.CharField(blank=True, max_length=120)),
                ('current_state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('work_authorization_country', models.CharField(blank=True, max_length=120)),
                ('salary_currency', models.CharField(blank=True, default='INR', max_length=8)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['updated_at'], name='candidates__updated_0f1a95_idx'), models.Index(fields=['location'], name='candidates__locatio_4a24c3_idx'), models.Index(fields=['notice_period_days'], name='candidates__notice__73c00e_idx'), models.Index(fields=['expected_salary'], name='candidates__expecte_836fa7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='candidates__name_f6da10_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateEmployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date'], name='candidates__start_d_0c1ece_idx'), models.Index(fields=['is_current'], name='candidates__is_curr_d4ce5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='candidates.candidateprofile')),
                ('status', models.CharField(blank=True, max_length=20)),
                ('worked_from_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('worked_from_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('worked_till_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('worked_till_month', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidateprofile')),
                ('course_type', models.CharField(blank=True, max_length=40)),
                ('marks_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-end_year', '-start_year'],
                'indexes': [models.Index(fields=['end_year'], name='candidates__end_yea_0e5679_idx')],
            },
        ),
    ]
