# Generated by Django 4.2.27 on 2026-01-21 06:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-end_year', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEmployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='candidateresume',
            name='candidate',
        ),
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skills_text',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='total_experience',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='total_experience_months',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='total_experience_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['updated_at'], name='candidates__updated_0f1a95_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['location'], name='candidates__locatio_4a24c3_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['notice_period_days'], name='candidates__notice__73c00e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['expected_salary'], name='candidates__expecte_836fa7_idx'),
        ),
        migrations.DeleteModel(
            name='CandidateResume',
        ),
        migrations.AddField(
            model_name='candidateskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidates.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidateproject',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='candidates.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidateemployment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='candidates.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidateprofile'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['name'], name='candidates__name_f6da10_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateemployment',
            index=models.Index(fields=['start_date'], name='candidates__start_d_0c1ece_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateemployment',
            index=models.Index(fields=['is_current'], name='candidates__is_curr_d4ce5c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateeducation',
            index=models.Index(fields=['end_year'], name='candidates__end_yea_0e5679_idx'),
        ),
    ]
