# Generated by Django 4.2.27 on 2026-02-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidateeducation_candidateemployment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='availability_to_join',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='location_country',
            field=models.CharField(default='India', max_length=60),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='profile-photos/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='work_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
