# Generated by Django 4.2.27 on 2026-02-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidateeducation_course_type_and_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateeducation',
            name='course_type',
            field=models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Correspondence/Distance learning', 'Correspondence/Distance learning')], max_length=40),
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='degree',
            field=models.CharField(choices=[('Doctorate/PhD', 'Doctorate/PhD'), ('Masters/Post-Graduation', 'Masters/Post-Graduation'), ('Graduation/Diploma', 'Graduation/Diploma'), ('12th', '12th'), ('10th', '10th'), ('Below 10th', 'Below 10th')], max_length=200),
        ),
    ]
