# Generated by Django 4.2.27 on 2026-02-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidateeducation_course_type_and_more'),
        ('candidates', '0005_candidateproject_status_and_dates'),
    ]

    operations = [
    ]
