# Generated by Django 4.2.27 on 2026-02-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_merge_20260211_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateeducation',
            name='course_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='degree',
            field=models.CharField(max_length=200),
        ),
    ]
