# Generated by Django 4.2.27 on 2026-02-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidateprofile_personal_details'),
        ('candidates', '0007_alter_candidateeducation_course_type_and_more'),
    ]

    operations = [
    ]
