# Generated by Django 4.2.27 on 2026-02-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidateprofile_salary_currency'),
        ('candidates', '0008_merge_20260212_1052'),
    ]

    operations = [
    ]
