# Generated by Django 4.2.27 on 2026-02-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_candidateprofile_notice_period_code_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidateprofile',
            new_name='candidates__notice__e07795_idx',
            old_name='candidates__notice_code_idx',
        ),
    ]
