# Generated by Django 4.2.27 on 2026-02-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_candidateskill_normalized_skill_fk'),
        ('candidates', '0013_rename_candidates__notice_code_idx_candidates__notice__e07795_idx'),
    ]

    operations = [
    ]
