# Generated by Django 4.2.27 on 2026-02-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_merge_20260220_1114'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidateskill',
            new_name='candidates__normali_b1977c_idx',
            old_name='candidates__skill_norm_idx',
        ),
    ]
