# Generated by Django 4.2.27 on 2026-02-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_candidateprofile_freshness_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidateprofile',
            new_name='candidates__created_2f4697_idx',
            old_name='candidates__created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='candidateprofile',
            new_name='candidates__last_ac_7286bc_idx',
            old_name='candidates__last_active_idx',
        ),
        migrations.RenameIndex(
            model_name='candidateprofile',
            new_name='candidates__profile_28902d_idx',
            old_name='candidates__profile_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='candidateprofile',
            new_name='candidates__freshne_664750_idx',
            old_name='candidates__freshness_idx',
        ),
    ]
