# Generated by Django 4.2.27 on 2026-02-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_backfill_profile_completion_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='profile_completion_percent',
        ),
    ]
