# Generated by Django 4.2.27 on 2026-02-27 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0020_remove_candidateprofile_profile_completion_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_completion_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
