# Generated by Django 4.2.27 on 2026-03-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_candidateprofile_profile_completion_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_locations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
