# Generated by Django 4.2.27 on 2026-01-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_groups'),
        ('accounts', '0002_update_roles_fields'),
    ]

    operations = [
    ]
