# Generated by Django 4.2.27 on 2026-02-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='skill',
            new_name='skills_skil_normali_e9faaa_idx',
            old_name='skills_skil_normal_51e33a_idx',
        ),
    ]
